# version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns         # Mount for experiment logs
      - ./backend:/mlflow/backend       # Optional DB storage
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/backend/mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
